// версия протобаф файла.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.12
// source: opcorpora.proto

// весь полученный из этого протобафа код добавляем в пакет service

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *ModeRequest) Reset() {
	*x = ModeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opcorpora_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeRequest) ProtoMessage() {}

func (x *ModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opcorpora_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeRequest.ProtoReflect.Descriptor instead.
func (*ModeRequest) Descriptor() ([]byte, []int) {
	return file_opcorpora_proto_rawDescGZIP(), []int{0}
}

func (x *ModeRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ModeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ModeResponse) Reset() {
	*x = ModeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opcorpora_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeResponse) ProtoMessage() {}

func (x *ModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opcorpora_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeResponse.ProtoReflect.Descriptor instead.
func (*ModeResponse) Descriptor() ([]byte, []int) {
	return file_opcorpora_proto_rawDescGZIP(), []int{1}
}

func (x *ModeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type FindWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *FindWordRequest) Reset() {
	*x = FindWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opcorpora_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindWordRequest) ProtoMessage() {}

func (x *FindWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opcorpora_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindWordRequest.ProtoReflect.Descriptor instead.
func (*FindWordRequest) Descriptor() ([]byte, []int) {
	return file_opcorpora_proto_rawDescGZIP(), []int{2}
}

func (x *FindWordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type WordProperty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Property string `protobuf:"bytes,1,opt,name=property,proto3" json:"property,omitempty"`
	Value    string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *WordProperty) Reset() {
	*x = WordProperty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opcorpora_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordProperty) ProtoMessage() {}

func (x *WordProperty) ProtoReflect() protoreflect.Message {
	mi := &file_opcorpora_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordProperty.ProtoReflect.Descriptor instead.
func (*WordProperty) Descriptor() ([]byte, []int) {
	return file_opcorpora_proto_rawDescGZIP(), []int{3}
}

func (x *WordProperty) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

func (x *WordProperty) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type WordRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word           string          `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Baseform       string          `protobuf:"bytes,2,opt,name=baseform,proto3" json:"baseform,omitempty"`
	WordProperties []*WordProperty `protobuf:"bytes,3,rep,name=word_properties,json=wordProperties,proto3" json:"word_properties,omitempty"`
}

func (x *WordRecord) Reset() {
	*x = WordRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opcorpora_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordRecord) ProtoMessage() {}

func (x *WordRecord) ProtoReflect() protoreflect.Message {
	mi := &file_opcorpora_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordRecord.ProtoReflect.Descriptor instead.
func (*WordRecord) Descriptor() ([]byte, []int) {
	return file_opcorpora_proto_rawDescGZIP(), []int{4}
}

func (x *WordRecord) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *WordRecord) GetBaseform() string {
	if x != nil {
		return x.Baseform
	}
	return ""
}

func (x *WordRecord) GetWordProperties() []*WordProperty {
	if x != nil {
		return x.WordProperties
	}
	return nil
}

type FindWordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result      string        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error       *string       `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	ReqId       *string       `protobuf:"bytes,4,opt,name=req_id,json=reqId,proto3,oneof" json:"req_id,omitempty"`
	WordRecords []*WordRecord `protobuf:"bytes,2,rep,name=word_records,json=wordRecords,proto3" json:"word_records,omitempty"`
}

func (x *FindWordResponse) Reset() {
	*x = FindWordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opcorpora_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindWordResponse) ProtoMessage() {}

func (x *FindWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opcorpora_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindWordResponse.ProtoReflect.Descriptor instead.
func (*FindWordResponse) Descriptor() ([]byte, []int) {
	return file_opcorpora_proto_rawDescGZIP(), []int{5}
}

func (x *FindWordResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *FindWordResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *FindWordResponse) GetReqId() string {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return ""
}

func (x *FindWordResponse) GetWordRecords() []*WordRecord {
	if x != nil {
		return x.WordRecords
	}
	return nil
}

type CheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opcorpora_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opcorpora_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_opcorpora_proto_rawDescGZIP(), []int{6}
}

func (x *CheckRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opcorpora_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opcorpora_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_opcorpora_proto_rawDescGZIP(), []int{7}
}

func (x *CheckResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type CheckFindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId string `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
}

func (x *CheckFindRequest) Reset() {
	*x = CheckFindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opcorpora_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFindRequest) ProtoMessage() {}

func (x *CheckFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opcorpora_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFindRequest.ProtoReflect.Descriptor instead.
func (*CheckFindRequest) Descriptor() ([]byte, []int) {
	return file_opcorpora_proto_rawDescGZIP(), []int{8}
}

func (x *CheckFindRequest) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

type CheckFindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result      string        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error       *string       `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	WordRecords []*WordRecord `protobuf:"bytes,2,rep,name=word_records,json=wordRecords,proto3" json:"word_records,omitempty"`
}

func (x *CheckFindResponse) Reset() {
	*x = CheckFindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opcorpora_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckFindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFindResponse) ProtoMessage() {}

func (x *CheckFindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opcorpora_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFindResponse.ProtoReflect.Descriptor instead.
func (*CheckFindResponse) Descriptor() ([]byte, []int) {
	return file_opcorpora_proto_rawDescGZIP(), []int{9}
}

func (x *CheckFindResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CheckFindResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *CheckFindResponse) GetWordRecords() []*WordRecord {
	if x != nil {
		return x.WordRecords
	}
	return nil
}

// Statistic info
type StatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opcorpora_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opcorpora_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_opcorpora_proto_rawDescGZIP(), []int{10}
}

func (x *StatRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error  *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Info   string  `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opcorpora_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opcorpora_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_opcorpora_proto_rawDescGZIP(), []int{11}
}

func (x *StatResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *StatResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *StatResponse) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_opcorpora_proto protoreflect.FileDescriptor

var file_opcorpora_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0x21, 0x0a, 0x0b, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x26, 0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x25, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x40, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x64, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x0a, 0x57, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x62,
	0x61, 0x73, 0x65, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62,
	0x61, 0x73, 0x65, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x48, 0x0a, 0x0f, 0x77, 0x6f, 0x72, 0x64, 0x5f,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x79, 0x52, 0x0e, 0x77, 0x6f, 0x72, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65,
	0x73, 0x22, 0xb8, 0x01, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x19,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12, 0x1a, 0x0a, 0x06, 0x72, 0x65, 0x71,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x72, 0x65, 0x71,
	0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x40, 0x0a, 0x0c, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x70,
	0x63, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0b, 0x77, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x22, 0x24, 0x0a, 0x0c,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x22, 0x27, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x29, 0x0a, 0x10, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x15, 0x0a, 0x06, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x22, 0x92, 0x01, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12,
	0x40, 0x0a, 0x0c, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x70, 0x6f, 0x72,
	0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x0b, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x21, 0x0a, 0x0b, 0x53,
	0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x5f,
	0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01,
	0x01, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32,
	0xa7, 0x03, 0x0a, 0x10, 0x4f, 0x70, 0x43, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x2e, 0x6f,
	0x70, 0x63, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6f,
	0x70, 0x63, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x55, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x22, 0x2e, 0x6f, 0x70,
	0x63, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x46, 0x69, 0x6e, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x23, 0x2e, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12,
	0x1f, 0x2e, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x69, 0x6e,
	0x64, 0x12, 0x23, 0x2e, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x70, 0x6f, 0x72, 0x61, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x46, 0x69, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x70, 0x6f,
	0x72, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49,
	0x0a, 0x04, 0x53, 0x74, 0x61, 0x74, 0x12, 0x1e, 0x2e, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x70, 0x6f,
	0x72, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6f, 0x70, 0x63, 0x6f, 0x72, 0x70, 0x6f,
	0x72, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2e, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_opcorpora_proto_rawDescOnce sync.Once
	file_opcorpora_proto_rawDescData = file_opcorpora_proto_rawDesc
)

func file_opcorpora_proto_rawDescGZIP() []byte {
	file_opcorpora_proto_rawDescOnce.Do(func() {
		file_opcorpora_proto_rawDescData = protoimpl.X.CompressGZIP(file_opcorpora_proto_rawDescData)
	})
	return file_opcorpora_proto_rawDescData
}

var file_opcorpora_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_opcorpora_proto_goTypes = []interface{}{
	(*ModeRequest)(nil),       // 0: opcorpora_service.ModeRequest
	(*ModeResponse)(nil),      // 1: opcorpora_service.ModeResponse
	(*FindWordRequest)(nil),   // 2: opcorpora_service.FindWordRequest
	(*WordProperty)(nil),      // 3: opcorpora_service.WordProperty
	(*WordRecord)(nil),        // 4: opcorpora_service.WordRecord
	(*FindWordResponse)(nil),  // 5: opcorpora_service.FindWordResponse
	(*CheckRequest)(nil),      // 6: opcorpora_service.CheckRequest
	(*CheckResponse)(nil),     // 7: opcorpora_service.CheckResponse
	(*CheckFindRequest)(nil),  // 8: opcorpora_service.CheckFindRequest
	(*CheckFindResponse)(nil), // 9: opcorpora_service.CheckFindResponse
	(*StatRequest)(nil),       // 10: opcorpora_service.StatRequest
	(*StatResponse)(nil),      // 11: opcorpora_service.StatResponse
}
var file_opcorpora_proto_depIdxs = []int32{
	3,  // 0: opcorpora_service.WordRecord.word_properties:type_name -> opcorpora_service.WordProperty
	4,  // 1: opcorpora_service.FindWordResponse.word_records:type_name -> opcorpora_service.WordRecord
	4,  // 2: opcorpora_service.CheckFindResponse.word_records:type_name -> opcorpora_service.WordRecord
	0,  // 3: opcorpora_service.OpCorporaService.Mode:input_type -> opcorpora_service.ModeRequest
	2,  // 4: opcorpora_service.OpCorporaService.FindWord:input_type -> opcorpora_service.FindWordRequest
	6,  // 5: opcorpora_service.OpCorporaService.Check:input_type -> opcorpora_service.CheckRequest
	8,  // 6: opcorpora_service.OpCorporaService.CheckFind:input_type -> opcorpora_service.CheckFindRequest
	10, // 7: opcorpora_service.OpCorporaService.Stat:input_type -> opcorpora_service.StatRequest
	1,  // 8: opcorpora_service.OpCorporaService.Mode:output_type -> opcorpora_service.ModeResponse
	5,  // 9: opcorpora_service.OpCorporaService.FindWord:output_type -> opcorpora_service.FindWordResponse
	7,  // 10: opcorpora_service.OpCorporaService.Check:output_type -> opcorpora_service.CheckResponse
	9,  // 11: opcorpora_service.OpCorporaService.CheckFind:output_type -> opcorpora_service.CheckFindResponse
	11, // 12: opcorpora_service.OpCorporaService.Stat:output_type -> opcorpora_service.StatResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_opcorpora_proto_init() }
func file_opcorpora_proto_init() {
	if File_opcorpora_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_opcorpora_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opcorpora_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opcorpora_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opcorpora_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordProperty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opcorpora_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opcorpora_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindWordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opcorpora_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opcorpora_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opcorpora_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckFindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opcorpora_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckFindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opcorpora_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opcorpora_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_opcorpora_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_opcorpora_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_opcorpora_proto_msgTypes[11].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_opcorpora_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_opcorpora_proto_goTypes,
		DependencyIndexes: file_opcorpora_proto_depIdxs,
		MessageInfos:      file_opcorpora_proto_msgTypes,
	}.Build()
	File_opcorpora_proto = out.File
	file_opcorpora_proto_rawDesc = nil
	file_opcorpora_proto_goTypes = nil
	file_opcorpora_proto_depIdxs = nil
}
